import type { Metadata } from 'next';
import '@/app/globals.css';

import SessionProvider from "@/utils/SessionProvider";
import { getServerSession } from 'next-auth';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function LoginLayout({ children, }: { children: React.ReactNode }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className='bg-gray-100 flex h-screen'>
        <SessionProvider session={session}>
          <div className='bg-[#FEFAEF] w-screen'>
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  )
}
