import type { Metadata } from 'next';
import '../globals.css';
import Footer from './Components/Footer';
import Header from './Components/Header';

import SessionProvider from "@/utils/SessionProvider";
import { getServerSession } from 'next-auth';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children, }: { children: React.ReactNode }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className='bg-gray-100 flex flex-col min-h-screen'>
        <SessionProvider session={session}>
          <Header />
          {children}
          {/* <Footer /> */}
        </SessionProvider>
      </body>
    </html>
  )
}
