import type { Metadata } from 'next'
import Footer from './Components/Footer'
import Header from './Components/Header'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gray-100 flex flex-col min-h-screen'>
        <Header />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  )
}
